//! Constants ported from defuddle's constants.ts.
//!
//! Selector lists, content indicators, and element sets used across the pipeline.

/// Entry point selectors for finding main content, in priority order.
/// Earlier entries are higher priority.
pub const ENTRY_POINT_SELECTORS: &[&str] = &[
    "#post",
    ".post-content",
    ".post-body",
    ".article-content",
    "#article-content",
    ".article_post",
    ".article-wrapper",
    ".entry-content",
    ".content-article",
    ".instapaper_body",
    ".post",
    ".markdown-body",
    "article",
    "[role=\"article\"]",
    "main",
    "[role=\"main\"]",
    ".article-body",
    "#content",
    "body",
];

/// Block elements for scoring.
pub const BLOCK_ELEMENTS: &[&str] = &[
    "div", "section", "article", "main", "aside", "header", "footer", "nav",
];

/// Exact selectors for clutter removal.
pub const EXACT_SELECTORS: &[&str] = &[
    "noscript",
    "script",
    "style",
    "meta",
    "link",
    "audio:not([src])",
    ".ad",
    "[role=\"banner\"]",
    ".promo",
    ".alert",
    "[id=\"comments\"]",
    "[id=\"comment\"]",
    "header:not(:has(p))",
    ".header",
    "#header",
    "#banner",
    "nav",
    ".navigation",
    "#navigation",
    "[role=\"navigation\"]",
    "[role=\"dialog\"]",
    "[role=\"complementary\"]",
    ".menu",
    "#siteSub",
    ".author",
    ".Author",
    "#categories",
    ".contributor",
    ".date",
    "#date",
    ".entry-meta",
    ".meta",
    ".tags",
    "#tags",
    "[rel=\"tag\"]",
    ".headline",
    "#headline",
    "#title",
    "#Title",
    ".toc",
    "#toc",
    "footer",
    ".aside",
    "aside:not([class*=\"callout\"])",
    "button",
    "canvas",
    "dialog",
    "fieldset",
    "form",
    "input:not([type=\"checkbox\"])",
    "label",
    "select",
    "textarea",
    "[hidden]",
    "[aria-hidden=\"true\"]",
    ".hidden",
    ".invisible",
    "iframe:not([src])",
    "#logo",
    "#newsletter",
    ".subscribe",
    ".noprint",
    ".sidebar",
    "#sidebar",
    "#secondary",
    ".copyright",
    "#copyright",
    "table.infobox",
    ".gh-header-sticky",
];

/// Partial selectors — matched against class/id attributes (case-insensitive).
pub const PARTIAL_SELECTORS: &[&str] = &[
    "advert",
    "ad-placement",
    "ads-container",
    "after_content",
    "afterpost",
    "article-author",
    "article-banner",
    "article-bottom",
    "article-category",
    "article-date",
    "article-header",
    "article-meta",
    "article-share",
    "article-tags",
    "article-title",
    "article-topics",
    "author-bio",
    "author-box",
    "author-info",
    "author-name",
    "avatar",
    "back-to-top",
    "backlink",
    "bio-block",
    "breadcrumb",
    "byline",
    "card-text",
    "card-media",
    "card-post",
    "catlinks",
    "comments",
    "-comment",
    "consent",
    "contact-",
    "content-card",
    "content-topics",
    "cover-image",
    "cover-photo",
    "dateline",
    "date-header",
    "date-pub",
    "disclaimer",
    "discussion",
    "disqus",
    "donate",
    "donation",
    "entry-author",
    "entry-categories",
    "entry-date",
    "entry-title",
    "eyebrow",
    "facebook",
    "favorite",
    "featured-content",
    "feedback",
    "feed-links",
    "footer",
    "footnote-back",
    "further-reading",
    "gist-meta",
    "hamburger",
    "header-logo",
    "hide-for-print",
    "hide-print",
    "infoline",
    "jumplink",
    "jumpto",
    "keepreading",
    "keep-reading",
    "kicker",
    "language-name",
    "lastupdated",
    "latest-content",
    "-license",
    "like-button",
    "loading",
    "logo_container",
    "masthead",
    "marketing",
    "-menu",
    "menu-",
    "metadata",
    "meta-bottom",
    "meta-date",
    "might-like",
    "minibio",
    "more-about",
    "more-",
    "morenews",
    "morestories",
    "most-read",
    "mw-editsection",
    "mw-cite-backlink",
    "mw-jump-link",
    "nav-",
    "nav_",
    "navigation-post",
    "next-",
    "next_prev",
    "newsletter_",
    "newsletter-form",
    "newsletter-signup",
    "noprint",
    "pagehead",
    "page-header",
    "page-title",
    "paywall",
    "-partners",
    "popular",
    "popup",
    "post-author",
    "post-bottom",
    "postcomment",
    "postdate",
    "post-date",
    "post-details",
    "post-info",
    "post-links",
    "post-meta",
    "post_meta",
    "post-navigation",
    "post-preview",
    "post-snippet",
    "posttag",
    "post-tag",
    "post-title",
    "prev-post",
    "prevnext",
    "prev-next",
    "print-none",
    "print-header",
    "privacy-notice",
    "privacy-settings",
    "profile",
    "promo-",
    "pubdate",
    "pub-date",
    "publish-date",
    "readmore",
    "read-next",
    "read-time",
    "reading-time",
    "recent-",
    "recent-articles",
    "recentpost",
    "recommend",
    "recirc",
    "register",
    "related",
    "relevant",
    "screen-reader-text",
    "scroll-to",
    "-search",
    "share-box",
    "share-icons",
    "share-post",
    "share-section",
    "sidebar-content",
    "sidebar-wrapper",
    "sidebar-item",
    "sign-in-gate",
    "similar-",
    "site-header",
    "site-logo",
    "site-name",
    "skip-content",
    "skip-to-content",
    "skip-link",
    "social-button",
    "social-shar",
    "speedbump",
    "sponsor",
    "sr-only",
    "story-date",
    "story-navigation",
    "submenu",
    "-subscribe-",
    "subscription-",
    "_tags",
    "tag-list",
    "tag-module",
    "taxonomy",
    "table-of-contents",
    "timestamp",
    "time-read",
    "time-to-read",
    "toolbar",
    "tooltip-content",
    "topbar",
    "subnavbar",
    "topic-footer",
    "topic-list",
    "trending",
    "twitter",
    "u-hide",
    "upsell",
    "visually-hidden",
    "widget_pages",
    "yarpp-related",
];

/// Content indicator class/id patterns (presence = likely content, skip removal).
pub const CONTENT_INDICATORS: &[&str] = &[
    "admonition",
    "article",
    "content",
    "entry",
    "image",
    "img",
    "font",
    "figure",
    "figcaption",
    "pre",
    "main",
    "post",
    "story",
    "table",
];

/// Navigation indicator text patterns.
pub const NAVIGATION_INDICATORS: &[&str] = &[
    "advertisement",
    "all rights reserved",
    "banner",
    "cookie",
    "comments",
    "copyright",
    "follow me",
    "follow us",
    "footer",
    "header",
    "homepage",
    "login",
    "menu",
    "more articles",
    "more like this",
    "most read",
    "nav",
    "navigation",
    "newsletter",
    "popular",
    "privacy",
    "recommended",
    "register",
    "related",
    "responses",
    "share",
    "sidebar",
    "sign in",
    "sign up",
    "signup",
    "social",
    "sponsored",
    "subscribe",
    "terms",
    "trending",
];

/// Content element selector — elements whose presence indicates real content.
pub const CONTENT_ELEMENT_SELECTOR: &str =
    "math, [data-mathml], .katex, pre, code, table, img, picture, video, blockquote, figure";

/// Footnote inline reference selectors.
pub const FOOTNOTE_INLINE_REFS: &str = concat!(
    "sup.reference, ",
    "a[href^=\"#fn\"], a[href^=\"#cite\"], a[href^=\"#footnote\"], ",
    "a[href*=\"cite_note\"], a[href*=\"cite_ref\"], ",
    "a[id^=\"fnref\"], sup[data-fn] > a[href^=\"#\"]"
);

/// Footnote list selectors.
pub const FOOTNOTE_LIST_SELECTORS: &str = concat!(
    "div.footnote ol, div.footnotes ol, ",
    "div[role=\"doc-endnotes\"], div[role=\"doc-footnotes\"], ",
    "ol.footnotes-list, ol.footnotes, ol.references, ",
    "section.footnotes ol, section[role=\"doc-endnotes\"], ",
    "section[role=\"doc-footnotes\"], section[role=\"doc-bibliography\"], ",
    "div.footnote-definitions, ol.wp-block-footnotes, #footnotes"
);
